version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py wait_for_db && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=debug
      - DB_PASS=debug
    depends_on:
      - db

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A accounting worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app

volumes:
  pgdata: